export const databaseQuotes = [
    { text: 'Hidup adalah 10% apa yang terjadi pada kita dan 90% bagaimana kita meresponnya.', author: 'Charles R. Swindoll' },
    { text: 'Kesuksesan tidaklah final, kegagalan tidaklah fatal.', author: 'Winston Churchill' },
    { text: 'Jangan biarkan kemarin mengambil terlalu banyak hari ini.', author: 'Will Rogers' },
    { text: 'Kamu tidak pernah terlalu tua untuk menetapkan tujuan baru.', author: 'C.S. Lewis' },
    { text: 'Kebahagiaan adalah kunci kesuksesan.', author: 'Albert Schweitzer' },
    { text: 'Kurang atau lebih, setiap rezeki perlu dirayakan dengan secangkir kopi.', author: 'Joko Pinurbo' },
    { text: 'Jangan khawatirkan apa yang dipikirkan orang lain. Tegakkan kepalamu dan melangkahlah ke depan', author: 'Izuku Midoriya' },
    { text: 'Kekuatan sejati dari umat manusia adalah bahwa kita memiliki kuasa penuh untuk mengubah diri kita sendiri.', author: 'Saitama' },
    { text: 'Jika kamu benar-benar ingin menjadi kuat... Berhentilah mempedulikan apa yang orang sekitar pikirkan tentangmu', author: 'Saitama' },
    { text: 'Kita mungkin tidak dapat memilih bagaimana kita mati, tapi kita bisa memutuskan bagaimana kita hidup.', author: 'Clare' },
    { text: 'Walaupun sudah lama tidak bertemu, tapi kamu harus tetap mengingat wajah temanmu.', author: 'Shino Aburame' },
    { text: 'Aku jatuh cinta padamu, bukan karena kelebihanmu, tapi karena kelemahanmu.', author: 'Chihiro Furuya' },
    { text: 'Cinta itu seperti angin, tidak bisa kulihat, tapi bisa kurasakan.', author: 'Mikan Sakura' },
    { text: 'Jika kamu tidak suka takdirmu, jangan terima. Sebaliknya, miliki keberanian untuk mengubahnya sesuai keinginanmu.', author: 'Naruto Uzumaki' },
    { text: 'Tolak akal sehat untuk membuat yang tidak mungkin menjadi mungkin.', author: 'Simon' },
    { text: 'Terkadang, berusaha untuk menjadi lebih baik adalah yang terbaik yang bisa kita lakukan.', author: 'Shinichi Kudo' },
    { text: 'Setiap orang memiliki masa lalu yang menyakitkan, tapi itu bukanlah alasan untuk menyerah pada masa depan', author: 'Itachi Uchiha' },
    { text: 'Hidup adalah sebuah petualangan, dan setiap keputusanmu akan membawamu ke arah yang berbeda.', author: 'Eren Yeager' },
    { text: 'Orang yang tidak mengerti rasa sakit tidak akan pernah mengerti kebahagiaan sejati.', author: 'Pain' },
    { text: 'Orang bodoh yang tidak menghargai masa lalu cenderung mengulanginya.', author: 'Nico Robin' },
    { text: 'Keadilan tanpa kekuatan adalah kekosongan, kekuatan tanpa keadilan adalah kekerasan.', author: 'Nanase Tsubasa' },
    { text: 'Efisiensi dan taktik yang matang menentukan hasil akhir dari sebuah pertempuran kode.', author: 'Kiyotaka Ayanokoji' }
];